import { redirect } from "next/navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Page() {
  redirect("/skill-test");

  return null;
}

export default Page;
